/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_alpha.h"
#include "bar_alternativetags.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "cyclelayouts.h"
#include "focusdir.h"
#include "focusmaster.h"
#include "focusurgent.h"
#include "fullscreen.h"
#include "maximize.h"
#include "moveplace.h"
#include "pertag.h"
#include "push.h"
#include "restartsig.h"
#include "rotatestack.h"
#include "scratchpad.h"
#include "selfrestart.h"
#include "shiftviewclients.h"
#include "sticky.h"
#include "swallow.h"
#include "tagallmon.h"
#include "togglefullscreen.h"
#include "transfer.h"
#include "vanitygaps.h"
#include "warp.h"
#include "winview.h"
#include "zoomswap.h"
#include "xrdb.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_bstackhoriz.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_gapplessgrid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

