/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_alpha.c"
#include "bar_alternativetags.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "autostart.c"
#include "cyclelayouts.c"
#include "focusdir.c"
#include "focusmaster.c"
#include "focusurgent.c"
#include "fullscreen.c"
#include "maximize.c"
#include "moveplace.c"
#include "pertag.c"
#include "push.c"
#include "restartsig.c"
#include "rotatestack.c"
#include "scratchpad.c"
#include "selfrestart.c"
#include "shiftviewclients.c"
#include "sticky.c"
#include "swallow.c"
#include "tagallmon.c"
#include "togglefullscreen.c"
#include "transfer.c"
#include "vanitygaps.c"
#include "warp.c"
#include "winview.c"
#include "zoomswap.c"
#include "xrdb.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_bstackhoriz.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_gapplessgrid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

